name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (system unusable)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (minor inconvenience)
    validations:
      required: true

  - type: dropdown
    id: user-role
    attributes:
      label: User Role
      description: What role were you using?
      options:
        - Traveler
        - Immigration Officer
        - ZIMRA Officer
        - Government Official
        - Administrator
        - Not logged in
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: What part of the system is affected?
      options:
        - Arrival Card Form
        - Dashboard
        - Authentication
        - QR Code Scanning
        - Email Notifications
        - API
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details.
      placeholder: |
        - Browser: Chrome 120
        - OS: Windows 11
        - Device: Desktop
        - Screen size: 1920x1080
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
      placeholder: Drag and drop images here

  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      description: If applicable, paste any browser console errors.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have provided all required information
          required: true
        - label: This is not a security vulnerability (use SECURITY.md instead)
          required: true
